// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAosIiTVqVuzdfqRcwV-wDmuA36ViE-Emw',
    appId: '1:862082955632:android:98db5b28e62a60c89cb7b5',
    messagingSenderId: '862082955632',
    projectId: 'teste-notificacao-barbearia',
    storageBucket: 'teste-notificacao-barbearia.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCX2odnSInjrKb5HdOLA5rGoXrv58e7dMQ',
    appId: '1:862082955632:ios:87bcdafd50c7c2109cb7b5',
    messagingSenderId: '862082955632',
    projectId: 'teste-notificacao-barbearia',
    storageBucket: 'teste-notificacao-barbearia.firebasestorage.app',
    androidClientId: '862082955632-7fidq55qp87pejp5n6v4u9v1uqdrkasb.apps.googleusercontent.com',
    iosClientId: '862082955632-l34tg6c5jff5vidigsobfr94i0ru5sr5.apps.googleusercontent.com',
    iosBundleId: 'com.ygg.barbearia1',
  );
}
